---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - fastsvc.fastsvc.tum
  resources:
  - fastsvcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fastsvc.fastsvc.tum
  resources:
  - fastsvcs/finalizers
  verbs:
  - update
- apiGroups:
  - fastsvc.fastsvc.tum
  resources:
  - fastsvcs/status
  verbs:
  - get
  - patch
  - update
