apiVersion: v1
kind: Pod
metadata:
  name: fastautoscaler 
spec:
  restartPolicy: OnFailure
  nodeName: gpu-one
  containers:
    - image: yukiozhu/fastautoscaler
      name: fastautoscaler
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default 
  name: fastsvc-list-role
rules:
- apiGroups:
  - fastsvc.fastsvc.tum
  resources:
  - fastsvcs
  verbs:
  - list

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fastsvc-list-rolebinding
  namespace: default 
subjects:
- kind: User # replace with "ServiceAccount" if using a service account
  name: # replace with the name of your user or service account
roleRef:
  kind: Role # replace with "ClusterRole" if using a ClusterRole
  name: fastsvc-list-role # replace with the name of the Role or ClusterRole you created
  apiGroup: rbac.authorization.k8s.io
